
package jp.freebit.databasetest.Realm;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.Index;

/**
 * Created by akihiroaida on 15/03/12.
 */
public class User2 extends RealmObject {

    @Index
    private String name;

    private int age;

    private String email;

    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
}
